# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ec4f2287cbce317d6d3af46b84baa1792e39a07c8eb17a412e5debfb33edce4c755bf41e706f8e6e740112d95c61f51a9e86bee7d3b1519fabb3d1d8fbf5fab

test:
  secret_key_base: 16b7c132fe982863bdc38e83b1d8036c108af9ac3c113e352415174a36175dc02d98d6d2833a73588c511bf5b006cd043a7f2be02a254f0e75e73c66c142410e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
